name: Build Executables

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install
        poetry add pyinstaller
    
    - name: Build with PyInstaller
      run: |
        poetry run pyinstaller main.spec
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: client-${{ matrix.os }}
        path: dist/
